### ISSUE TITLE
Encountered a failure during backup

### ISSUE THREAD

**Issue by ertanner** [cloudback/issue-tracker#23]
**Describe the bug**
I recieve the following error:
"Error during backup:
Access Denied: AuthenticationErrorDetail: Signature not valid in the specified time frame: Start [Mon, 22 Apr 2024 19:50:13 GMT] - Expiry [Tue, 23 Apr 2024 03:50:13 GMT] - Current [Wed, 24 Apr 2024 01:14:23 GMT];"
This occurred on three of my repos.  I believe i have enough disk space (5Tb).

What does this error mean and suggestions for fixing it?

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser chrome
 - Version 123.0.6312.87

**Comment by arxange1** [comment]
Dear @ertanner. 
Your `Azure Blob Container` is connected to Cloudback using [Shared Access Signature (SAS)](https://learn.microsoft.com/en-us/azure/storage/common/storage-sas-overview). The issued signature is with validity period of 1 day only, from 22 till 23 April. Now the signature is expired, that's why the access is denied. 

You need to generate a new `Shared Access Signature` and update it in the storage editor by the [link](https://app.cloudback.it/storages/edit/550)
