### ISSUE TITLE
unpacking downloaded backup fails

### ISSUE THREAD

**Issue by solexperts-tor** [cloudback/issue-tracker#33]
**Describe the bug**
When downloading a backup from the dashboard, the downloaded ZIP file results in ZIP/Windows throwing an error. ZIP does not ask for a password. It seems as if there is a ZIP file contained in the downloaded ZIP, which throws a different Windows error, when opened.

**To Reproduce**
1. In dashboard use "Download this backup" on a repository
2. Go to download location on client
3. Unzip downloaded backup
4. Choose unzip destination
5. See error

**Expected behavior**
When unzipping the downloaded backup, I expect to choose a unzip destination and put in a password. Afterwards the unzipped directory should be available at the chosen destination. 

**Screenshots**
![image](https://github.com/user-attachments/assets/8017c53d-3821-4732-8dd5-d7091170f3ab)
![image](https://github.com/user-attachments/assets/313bee47-da7e-4696-b61f-f0df6084f7f2)

**Desktop (please complete the following information):**
 - OS: Windows 11 23H2
 - Browser: Brave 1.70.119

**Comment by arxange1** [comment]
Dear @solexperts-tor,

Thank you for reporting this issue and providing detailed steps to reproduce it.

The error you're encountering is likely due to the fact that Windows' built-in ZIP tool does not support AES encryption, which is used in the backup ZIP files. Instead of using the default Windows unzip utility, we recommend using **7-Zip**, which fully supports AES-encrypted ZIP files. 

You can download 7-Zip from [here](https://www.7-zip.org/). Once installed, you should be able to extract the backup by right-clicking the ZIP file, selecting **7-Zip > Extract**, and entering the required password when prompted.

Please try this and let us know if the issue persists!

Best regards,  
Victor

**Comment by solexperts-tor** [comment]
Ah, thanks for the clarification and sorry about opening this issue.
